### ISSUE TITLE
Package versions do not show up on pkg.go.dev

### ISSUE THREAD

**Issue by dekimsey** [zloylos/grsync#12]
I noticed the versioned releases (such as 1.3.0) don't show up on pkg.go.dev. My initial guess is that go.dev expects the tags to have a `v` prefix.

https://pkg.go.dev/github.com/zloylos/grsync?tab=versions

Thank you

**Comment by zloylos** [comment]
I fixed the latest version name. Now looks good. 
All next versions will be start from `v` prefix. 
Thank you!
